// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asnrihqbhtaqwxqubmjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzbnJpaHFiaHRhcXd4cXVibWp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NzM4MjUsImV4cCI6MjA3MjU0OTgyNX0.wfiibF9hvHAfg5BAO8HKAI17CFWyqQ_ADRv1r0CVd4w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});